device: 0
lr: 0.0001
model_name: resnet18
batchsize: 64
logspace: 0
gamma: 0.9
momentum: 0.9
weight_decay: 0.00001
epoch: 60
seed: 0
opt: adam
datapath: ./eigen_FER2013
result_path: result_resnet18
pickle_path: pickle
eigen: True
start_epoch: 0
