device: 0
lr: 0.0001
model_name: resnet18
batchsize: 64
logspace: 1
gamma: 0.9
momentum: 0.9
weight_decay: 0.00001
epoch: 60
seed: 0
opt: adam
datapath: /content/FER2013
result_path: result_resnet18_finetune
pickle_path: eigenface_pickle/pickle
eigen: False
start_epoch: 0
finetune: True
finetune_path: /content/result_resnet18/model_59.bin
